from enum import Enum

class Role(Enum):
    GIS = 1
    MAYOR = 2
    ASSESSOR = 3

stateCorrectionMap = {
    ("al", "alabama"): "AL – Alabama",
    ("ak", "alaska"): "AK – Alaska",
    ("az", "arizona"): "AZ – Arizona",
    ("ar", "arkansas"): "AR – Arkansas",
    ("ca", "california"): "CA – California",
    ("co", "colorado"): "CO – Colorado",
    ("ct", "connecticut"): "CT – Connecticut",
    ("de", "delaware"): "DE – Delaware",
    ("fl", "florida"): "FL – Florida",
    ("ga", "georgia"): "GA – Georgia",
    ("hi", "hawaii"): "HI – Hawaii",
    ("id", "idaho"): "ID – Idaho",
    ("il", "illinois"): "IL – Illinois",
    ("in", "indiana"): "IN – Indiana",
    ("ia", "iowa"): "IA – Iowa",
    ("ks", "kansas"): "KS – Kansas",
    ("ky", "kentucky"): "KY – Kentucky",
    ("la", "louisiana"): "LA – Louisiana",
    ("me", "maine"): "ME – Maine",
    ("md", "maryland"): "MD – Maryland",
    ("ma", "massachusetts"): "MA – Massachusetts",
    ("mi", "michigan"): "MI – Michigan",
    ("mn", "minnesota"): "MN – Minnesota",
    ("ms", "mississippi"): "MS – Mississippi",
    ("mo", "missouri"): "MO – Missouri",
    ("mt", "montana"): "MT – Montana",
    ("ne", "nebraska"): "NE – Nebraska",
    ("nv", "nevada"): "NV – Nevada",
    ("nh", "new hampshire"): "NH – New Hampshire",
    ("nj", "new jersey"): "NJ – New Jersey",
    ("nm", "new mexico"): "NM – New Mexico",
    ("ny", "new york"): "NY – New York",
    ("nc", "north carolina"): "NC – North Carolina",
    ("nd", "north dakota"): "ND – North Dakota",
    ("oh", "ohio"): "OH – Ohio",
    ("ok", "oklahoma"): "OK – Oklahoma",
    ("or", "oregon"): "OR – Oregon",
    ("pa", "pennsylvania"): "PA – Pennsylvania",
    ("ri", "rhode island"): "RI – Rhode Island",
    ("sc", "south carolina"): "SC – South Carolina",
    ("sd", "south dakota"): "SD – South Dakota",
    ("tn", "tennessee"): "TN – Tennessee",
    ("tx", "texas"): "TX – Texas",
    ("ut", "utah"): "UT – Utah",
    ("vt", "vermont"): "VT – Vermont",
    ("va", "virginia"): "VA – Virginia",
    ("wa", "washington"): "WA – Washington",
    ("wv", "west virginia"): "WV – West Virginia",
    ("wi", "wisconsin"): "WI – Wisconsin",
    ("wy", "wyoming"): "WY – Wyoming",
    # Canadian provinces & territories
    ("ab", "alberta"): "AB – Alberta",
    ("bc", "british columbia"): "BC – British Columbia",
    ("mb", "manitoba"): "MB – Manitoba",
    ("nb", "new brunswick"): "NB – New Brunswick",
    ("nl", "newfoundland and labrador"): "NL – Newfoundland and Labrador",
    ("ns", "nova scotia"): "NS – Nova Scotia",
    ("nt", "northwest territories"): "NT – Northwest Territories",
    ("nu", "nunavut"): "NU – Nunavut",
    ("on", "ontario"): "ON – Ontario",
    ("pe", "prince edward island"): "PE – Prince Edward Island",
    ("qc", "quebec"): "QC – Quebec",
    ("sk", "saskatchewan"): "SK – Saskatchewan",
    ("yt", "yukon"): "YT – Yukon"
}
